---
name: Coverage
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run coverage check.
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade nox
      - name: Run coverage check
        run: |
          nox --session coverage
