---
name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade nox
      - name: Run linters
        run: |
          nox -k lint
      - name: Run security checks
        run: |
          nox -k security
