---
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - python: '3.10.1'
            minor: '3.10'
          - python: '3.9.9'
            minor: '3.9'
          - python: '3.8.12'
            minor: '3.8'
          - python: '3.7.12'
            minor: '3.7'
    name: Test with Python ${{ matrix.python-version.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade nox
      - name: Run tests
        run: |
          nox --session test --python ${{ matrix.python-version.minor }}
